CREATE TABLE recipes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL CHECK (length(slug) BETWEEN 1 AND 120),
  title TEXT NOT NULL,
  markdown TEXT NOT NULL,
  view_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
