export const EDIT_ERROR_CODES = {
  INVALID_EDIT_LINK: "INVALID_EDIT_LINK",
  EDIT_LINK_NOT_FOUND: "EDIT_LINK_NOT_FOUND",
  INVALID_RECIPE_FIELDS: "INVALID_RECIPE_FIELDS",
  INVALID_RECIPE_SLUG: "INVALID_RECIPE_SLUG",
  RECIPE_SLUG_TAKEN: "RECIPE_SLUG_TAKEN",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type EditErrorCode =
  (typeof EDIT_ERROR_CODES)[keyof typeof EDIT_ERROR_CODES];
